[technote]
id = "DMTN-294"
series_id = "DMTN"
canonical_url = "https://dmtn-294.lsst.io"
github_url = "https://github.com/lsst-dm/dmtn-294"
github_default_branch = "main"
date_created = 2024-07-22T17:02:08Z
organization.name = "Vera C. Rubin Observatory"
organization.ror = "https://ror.org/048g3cy84"
license.id = "CC-BY-4.0"

[technote.status]
state = "draft"

[[technote.authors]]
name.given = "James F."
name.family = "Bosch"
internal_id = "boschjf"
orcid = "https://orcid.org/0000-0003-2759-5764"
[[technote.authors.affiliations]]
name = "Department of Astrophysical Sciences"
internal_id = "Princeton-Astro"
address = "Princeton University, Princeton, NJ 08544, USA"
